recipe/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recipe_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

recipe/recipe_app/urls.py
from django.urls import path
from . import views

app_name = "recipe_app"



urlpatterns = [
    path('', views.home, name="home"),
    path('add_recipe/', views.add_recipe, name="add_recipe_with_form"),
    path('all_recipe/', views.all_recipe, name="recipes"),
]

recipe/recipe_app/models.py
from django.db import models


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    ingredients = models.TextField(max_length=1500)
    instructions = models.TextField(max_length=1500)
    cooking_time = models.PositiveBigIntegerField()
    image = models.ImageField(upload_to="recipe/", blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
# Create your models here.

recipe/recipe_app/forms.py
from django import forms

from .models import Recipe

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["name", "ingredients", "instructions", "cooking_time", "image"]
 

recipe/recipe_app/views.py
from django.shortcuts import render, redirect

from .models import Recipe
from .forms import RecipeForm


# Create your views here.

def home(request):
    return render(request, "recipe/home.html", {"home": home})


def add_recipe(request):

    form = RecipeForm()

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("recipe_app:recipes")
    
    context = {
        "form":form
    }

    return render(request, "recipe/add_recipe_with_form.html", context)


def all_recipe(request):
    all_recipe = Recipe.objects.all()
    return render(request, "recipe/all_recipe.html", {"recipes":all_recipe})

recipe/templates/partials/base.html
{% load static %}

<title>{% block title %} Recipe {% endblock title %}</title>

{% block header %}
{% include "partials/header.html" %}
{% endblock header %}

{% block content %}

{% endblock content %}

{% block footer %}
{% include "partials/footer.html" %}
{% endblock footer %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock links %}

recipe/templates/partials/footer.html
 <footer>
        <div class="footer-content">
            Django Assignment 2025
        </div>
</footer>

recipe/templates/partials/header.html
<header>

<nav>
    <ul>
        <li><a href="{% url 'recipe_app:home' %}">Home</a></li>
        <li><a href="{% url 'recipe_app:add_recipe_with_form' %}">Add Recipe</a></li>
        <li><a href="{% url 'recipe_app:recipes' %}">All Recipes</a></li>
    </ul>
</nav>

</header>