music_store/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("music_store.urls")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

music_store/music_store/urls.py
from django.urls import path

from . import views

app_name = 'music_store'

urlpatterns = [
    path('', views.home, name="home"),
    path('artist/', views.artist_listing, name="artists"),
    path('all-albums/', views.album_listing, name="all-albums"),
    path('albums/<int:artist_id>/', views.artist_album, name="author-albums"),
    path('artist/<int:artist_id>/', views.artist_detail, name="artist-detail"),
    path('album/<int:album_id>/', views.album_detail, name="album-detail"),
]

music_store/music_store/models.py
from django.db import models

from datetime import date
from django.utils import timezone

from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError

# Create your models here.

class Artist(models.Model):
    name = models.CharField(max_length=255, validators=[MinLengthValidator(2)])
    debut_year = models.IntegerField()
    artist_image = models.ImageField(upload_to= "artist-images", blank=True ,null=True)

    def __str__(self):
        return f"{self.name} | {self.debut_year}"


def release_date_validator(release_date):
    min_date = date(1800, 1, 1)
    current_date = timezone.now().date()
    
    if  not (min_date <= release_date <= current_date):
        raise ValidationError(f"The release date cannot be earlier than 1800 and cannot be in the future ")
    

class Album(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name="Albums")
    title = models.CharField(max_length=255)
    release_date = models.DateField(validators=[release_date_validator])
    album_image = models.ImageField(upload_to= "album-images", blank=True ,null=True)

    def __str__(self):
        return f"{self.title} | {self.artist.name} - {self.release_date}"

music_store/music_store/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from .models import Artist
from .models import Album


def home(request):

    return render(request, "music-store/home.html")


def artist_listing(request):

    get_all_artists = Artist.objects.order_by("debut_year")
    
    return render(request, "music-store/artist-listing.html", {"all_artists": get_all_artists})

def album_listing(request):

    get_all_albums = Album.objects.order_by("-release_date")
    return render(request, "music-store/album-listing.html", {"all_albums": get_all_albums})


def artist_album(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)  
    get_artist_albums = Album.objects.order_by("-release_date")  

    context = {
        "artist": artist,
        "artist_albums": get_artist_albums
    }
    
    return render(request, "music-store/artist-album.html", context)

def artist_detail(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)  

    return render(request, "music-store/artist_detail.html", {"artist": artist})

def album_detail(request, album_id):
    album = get_object_or_404(Album, id=album_id)  

    return render(request, "music-store/album_detail.html", {"album": album})

music_store/templates/music-store/album-listing.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}All Albums{% endblock title %}

{% block contents %}
<div class="artist-container">
    <h1>All Albums</h1>
    <h4>Explore our collection of albums and their artists.</h4>
    
    <ol class="artist-list">
        {% for album in all_albums %}
            <li>
                <strong><a href="{% url 'music_store:album-detail' album.pk %}">{{ album.title }}</a></strong> 
            </li>
        {% endfor %}
    </ol>
</div>
{% endblock contents %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock links %}

music_store/templates/music-store/album_detail.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}Album Detail View{% endblock title %}

{% block contents %}
<div class="artist-albums-container">
    <h3>This album was produced by {{ album.artist.name }}</h3>
    
    <div class="album-info">
        <strong>{{ album.title }}</strong>
        <span class="release-date">Released on: {{ album.release_date }}</span>
        <span class="artist-name">by <a href="{% url 'music_store:artist-detail' album.artist.pk %}">
    {{ album.artist.name }}
</a></span>

            {% if album.album_image %}
        <img src="{{ album.album_image.url }}" alt="{{ album.title }} Image">
    
    {% else %}
        <p> No picture yet</p>
    {% endif %}
    </div>
</div>
{% endblock contents %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock links %}

 

music_store/templates/music-store/artist-album.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}All {{ artist.name }} Albums{% endblock title %}

{% block contents %}
<div class="artist-albums-container">
    <h3>All Albums by {{ artist.name }}</h3>
    
    <ul class="album-list">
        {% for album in artist.Albums.all %}
            <li class="album-item">
                <div class="album-info">
                    <strong>{{ album.title }}</strong>
                    <span class="release-date">Released on: {{ album.release_date }}</span>
                    <span class="artist-name">by {{ album.artist.name }}</span>
                      {% if album.album_image %}
                    <img src="{{ album.album_image.url }}" alt="{{ album.title }} Image">
                
                {% else %}
                    <p> No picture yet</p>
                {% endif %}
                </div>
            </li>
        {% empty %}
            <li>No albums found for this artist.</li>
        {% endfor %}
    </ul>
</div>
{% endblock contents %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock links %}

 

music_store/templates/music-store/artist-listing.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}All Artists{% endblock title %}

{% block contents %}
<div class="artist-container">
    <h1>Discover Our Artists</h1>
    <h4>Click on an artist to explore their albums.</h4>
    
    <ol class="artist-list">
        {% for artist in all_artists %}
            <li>
                <a href="{% url 'music_store:artist-detail' artist.pk %}">
                    {{ artist.name }} 
                </a>
               
            </li>
        {% endfor %}
    </ol>
</div>
{% endblock contents %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock links %}

music_store/templates/music-store/artist_detail.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}All Artists{% endblock title %}

{% block contents %}
<div class="artist-container">
    <h1>Discover this Artist and Their Journey</h1>

    <div class="artist-card">
        <h2 class="artist-name">{{ artist.name }}</h2>
        <span class="debut-year">Debuted in {{ artist.debut_year }}</span>

        {% if artist.artist_image %}
            <img src="{{ artist.artist_image.url }}" alt="{{ artist.name }} Image" class="artist-image">
        {% else %}
            <p class="no-image-text">No picture yet</p>
        {% endif %}
    </div>

    <p class="album-link">
        <a href="{% url 'music_store:author-albums' artist.pk %}" class="album-btn">View Their Albums Here</a>
    </p>
</div>
{% endblock contents %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock links %}

music_store/templates/music-store/home.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}Homepage{% endblock title %}

{% block contents %}
<div class="homepage-container">
    <h1>Welcome to Music Store</h1>
    <p>Explore amazing artists and their albums.</p>
    
    <div class="homepage-links">
        <a href="{% url 'music_store:artists' %}" class="btn">View All Artists</a>
        <a href="{% url 'music_store:all-albums' %}" class="btn">View All Albums</a>
    </div>
</div>
{% endblock contents %}

{% block links %}
<link rel="stylesheet" href=" {% static 'css/style.css' %}">
{% endblock links %}

music_store/templates/partials/base.html
<title> {% block title %}
Music Store 
{% endblock title %} </title>

{% block header %}
{% include "partials/header.html" %}
{% endblock header %}


{% block contents %}{% endblock contents %}


{% block footer %}
{% include "partials/footer.html" %}
{% endblock footer %}

{% block links %}

{% endblock links %}

music_store/templates/partials/footer.html
{% load static %}


<footer>
    <p>Music Store Assignment</p>
</footer>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

music_store/templates/partials/header.html
{% load static  %}

<header>
    <nav>
        <ul>
            <li><a href="{% url 'music_store:home' %}">Home</a></li>
            <li><a href="{% url 'music_store:artists' %}">All Artists</a></li>
            <li><a href="{% url 'music_store:all-albums' %}">All Albums</a></li>
        </ul>
    </nav>
</header>

<link rel="stylesheet" href="{% static 'css/style.css' %}">