movie_collection_system/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_collection_app.urls')),
    path('user/', include('user.urls')),
    
]


urlpatterns += static(
    settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
)

movie_collection_system/movie_collection_app/urls.py
from django.urls import path

from . import views

app_name = 'movie_collection_app'


urlpatterns = [
    path('', views.all_movies, name='all_movies'),
    path('create-movie/', views.create_movie, name='create_movie'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('update_movie/<int:movie_pk>/', views.update_movie, name='update_movie'),
    path('confirm_delete_movie/<int:movie_id>/', views.confirm_delete, name='confirm_delete'),
    path('delete_movie/<int:movie_id>/', views.delete_movie, name='delete_movie'),
]

movie_collection_system/user/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LoginView,LogoutView


app_name = 'user'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

movie_collection_system/movie_collection_app/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model

User = get_user_model()


from django.utils import timezone
from datetime import date

def release_date_validator(release_date):
    min_date = date(1800, 1, 1)
    current_date = timezone.now().date()
    
    if  not (min_date <= release_date <= current_date):
        raise ValidationError(f"The release date cannot be earlier than 1800 and cannot be in the future ")


# Create your models here.

class GenreChoices(models.TextChoices):
    ACTION = 'AC', 'Action'
    DRAMA = 'DR', 'Drama'
    COMEDY = 'CO', 'Comedy'
    HORROR = 'HO', 'Horror'
    ROMANCE = 'RO', 'Romance'
    SCIFI = 'SF', 'Science Fiction'
    FANTASY = 'FA', 'Fantasy'
    DOCUMENTARY = 'DO', 'Documentary'
    THRILLER = 'TH', 'Thriller'

class Movie(models.Model):
    title = models.CharField(max_length=255, help_text='Title of the Movie')
    director = models.CharField(max_length=255, help_text='Name of the Movie Director')
    release_date = models.DateField(validators=[release_date_validator], help_text='Release Date of your Movie')
    description = models.TextField(help_text='A Brief Description of your Movie')
    poster = models.ImageField(upload_to="movies", default='default-image.jpeg', help_text='Movie Poster')
    genre = models.CharField(max_length=2, choices=GenreChoices.choices, default=GenreChoices.DRAMA)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    

movie_collection_system/user/models.py
from django.db import models

# Create your models here.

movie_collection_system/movie_collection_app/forms.py
from django import forms

from .models import Movie, GenreChoices

class CreateMovie(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'director', 'release_date', 'description', 'poster', 'genre']



class UpdateMovie(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'director', 'release_date', 'description', 'poster', 'genre']



class MovieSearchForm(forms.Form):
    title = forms.CharField(max_length=255, required=False)

class FilterByGenre(forms.Form):
    genre = forms.ChoiceField(choices=GenreChoices.choices, required=False)

movie_collection_system/movie_collection_app/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.urls import reverse

from .models import Movie
from .forms import CreateMovie, UpdateMovie, MovieSearchForm, FilterByGenre

from django.contrib.auth.decorators import login_required
from django.contrib import messages



def all_movies(request):
    all_movies = Movie.objects.all()
    form = MovieSearchForm(request.GET)

    if form.is_valid():
        title = form.cleaned_data.get('title')
        if title:
            all_movies = all_movies.filter(title__icontains = title)
    

    filter_form = FilterByGenre(request.GET)
    
    if filter_form.is_valid():
        genre = filter_form.cleaned_data.get('genre')
        if genre:
            all_movies = all_movies.filter(genre=genre)

    return render(request, 'movies/all_movies.html', {'movies':all_movies, "filter_form":filter_form})

@login_required
def create_movie(request):
    form = CreateMovie()

    if request.method == 'POST':
        form = CreateMovie(request.POST, request.FILES)
        if form.is_valid():

            new_movie = form.save(commit=False)
            new_movie.added_by = request.user
            new_movie.save()
            messages.success(request, 'Movie Created Successfully')
            return redirect('movie_collection_app:all_movies')
    
    context = {

        "form": form
    }
    return render(request, 'movies/create_movie.html', context)

@login_required
def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    return render(request, 'movies/movie_detail.html', {'movie':movie})

@login_required
def update_movie(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user != movie.added_by:
        messages.error(request, 'You do not have permission to update the Movie')
        return redirect('movie_collection_app:all_movies')
    
    update_movie = UpdateMovie(instance=movie)

    if request.method == 'POST':
        update_movie = UpdateMovie(request.POST, request.FILES, instance=movie)
        if update_movie.is_valid():
            update_movie.save()
            messages.success(request, 'You have Sucessfully updated a Movie')
            return redirect(reverse('movie_collection_app:movie_detail',kwargs={'movie_id': movie.id}))
    
    context = {

        "movie": movie,
        "form": update_movie
    }

    return render(request, 'movies/update_movies.html', context)

@login_required
def confirm_delete(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.user != movie.added_by:
        messages.error(request, 'You do not have permission to delete the Movie')
        return redirect('movie_collection_app:all_movies')

    
    return render(request, 'movies/confirm_delete.html', {'movie':movie})

@login_required
def delete_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.user != movie.added_by:
        messages.error(request, 'You do not have permission to delete the Movie')
        return redirect('movie_collection_app:all_movies')

    if request.method == 'POST':
        movie.delete()
        messages.success(request, 'You have Suceesfully deleted a Movie')
        return redirect('movie_collection_app:all_movies')

movie_collection_system/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.


def signup(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Account Created Successfully')
            return redirect('user:login')
    
    context = {
        'form':form,
    }

    return render(request, 'user/signup.html', context)

movie_collection_system/templates/partials/base.html
{% load static %}

<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    
    {% block links %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'js/base.js' %}"></script>
    {% endblock links %}


    <style>
    .success {
        color:green;
    }

    .error {
        color:red;
    }

    .info {
        color:black;
    }

    </style>
</head>

<body>
    <div id="page-wrapper" class="page-container">
        {% block header %}
        <header id="main-header" class="site-header">
            <nav id="main-navigation" class="primary-nav">
                <a href="{% url 'movie_collection_app:all_movies' %}" id="home-link" class="nav-link">Go Back Home</a>
                    <div class="user-auth">
                        {% if request.user.is_authenticated %}
                            <span class="welcome-text">Welcome, {{ request.user }}</span>
                            <form action="{% url 'user:logout' %}" method="POST" class="logout-form">
                                {% csrf_token %}
                                <button type="submit" class="auth-button logout-button">Logout</button>
                            </form>
                        {% else %}
                            <a href="{% url 'user:login' %}" class="auth-button login-button">Login</a>
                        {% endif %}
                    </div>
            </nav>
        </header>

        {% if messages %}
            <div id="message-container">
                <ul>
                    {% for message in messages %}
                        <li class='{{ message.tags }}'>
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% endblock header %}

        <main id="main-content" class="content-wrapper">
            {% block content %}

            {% endblock content %}
        </main>

        {% block footer %}
        <footer id="main-footer" class="site-footer">
            <div id="footer-content" class="footer-text">
                Django Assignment 2025
            </div>
        </footer>
        {% endblock footer %}
    </div>

</body>
</html>

movie_collection_system/templates/user/login.html
{% extends "partials/base.html" %} 

{% load static %} 

{% block title %} 
  Login
{% endblock title %} 

{% block content %} 
<div class="login-container">
    <form action="{% url 'user:login' %}" method='POST' class="login-form">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="error-container">
                {% for error in form.non_field_errors %}
                    <p class="error-message">{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-input">
            {% for error in form.username.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-input">
            {% for error in form.password.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}
        </div>

        <button type="submit" class="login-btn">Log In</button>
    </form>

    <div class="signup-link">
        <p>Don't have an account? <a href="{% url 'user:signup' %}">Sign up</a></p>
    </div>
</div>
{% endblock content %} 

{% block links %} 
<link rel="stylesheet" href="{% static 'css/login.css' %}"> 
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<script src="{% static 'js/base.js' %}"></script>
{% endblock links %}

movie_collection_system/templates/user/signup.html
{% extends "partials/base.html" %} 
 
{% load static %} 
 
 
{% block title %} 
  Sign Up
{% endblock title %} 
 
 
{% block content %} 

<div class="login-container">
        <form action="{% url 'user:signup' %}" method='POST' class="login-form">
        {% csrf_token %}

        {% if form.non_field_errors %}

            <div class="error-container">

                {% for error in form.non_field_errors %}
                    <p class="error-message">{{ error }}</p>

                {% endfor %}
            </div>

        {% endif %}

        <div class="form-group">
            <label for="username">Enter a Username</label>
            <input type="text" name='username' class="form-input">
            {% for error in form.username.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="form-group">
            <label for="password1"> Enter a Password </label>
            <input type="password" name='password1' class="form-input">
            {% for error in form.password1.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="form-group">
            <label for="password2"> Confirm Password </label>
            <input type="password" name='password2' class="form-input">

            {% for error in form.password2.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}
        </div>
        <button type='submit' class="signup-btn"> Sign Up</button>
    </form>

    <div class="login-link">
    <p>Already have an Account? <a href="{% url 'user:login' %}">Log In</a></p>
    </div>
</div>





{% endblock content %} 
 
{% block links %} 
<link rel="stylesheet" href="{% static 'css/signup.css' %}"> 
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<script src="{% static 'js/base.js' %}"></script>
{% endblock links %}


    