lms/authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.home, name='home'),
    path('book-list/', views.book_list, name='book_list'),
]

lms/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include("library.urls")),
    path('authors/', include("authors.urls")),
    path('dtl', include("dtl.urls")),
]

lms/dtl/urls.py
from django.urls import path

from . import views

app_name = "dtl"


urlpatterns = [
    path('', views.cart, name="cart"),
]

lms/library/urls.py
from django.urls import path

from . import views

app_name = 'library'

urlpatterns = [
    path('all-authors/', views.all_authors, name='authors'),
    path('book-signings/', views.book_signings, name='book_signings'),
    path('all-books/', views.all_books, name='all_books'),
    path('book-detail/<int:book_id>/', views.book_detail, name='book_detail'),


]

lms/authors/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birth_date = models.DateField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

lms/library/models.py
from django.db import models

# Create your models here.

from authors.models import Author

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    num_of_pages = models.PositiveIntegerField()
    published_on = models.DateField()
    cover_image = models.ImageField(upload_to="book-covers/", blank=True, null=True)

    def __str__(self):
        return f"{self.title} published by {self.author}"

lms/authors/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "authors/home.html")

def book_list(request):
    return render(request, "authors/book-list.html")

lms/dtl/views.py
from django.shortcuts import render

# Create your views here.

def cart(request):

    context = {
        "user": "Jesu",
        "cart": ["tomato", "strawberry", "vanilla Ice Cream", "burger", "cake"],
        "is_favorite": True,
        "no_of_items": 5,
    }

    return render(request, "dtl/cart.html", context)

lms/library/views.py
from django.shortcuts import render, get_object_or_404


from library.models import Book
from authors.models import Author

# Create your views here.
def all_authors(request):
    return render(request, "library/all-authors.html")


def book_signings(request):
    return render(request, "library/book-signings.html")


def all_books(request):

    all_books = Book.objects.order_by("-title")

    all_books_after_2000 = Book.objects.filter(published_on__gt = "2000-01-01")
    
    first_author = Author.objects.first()

    books_greater_than_200_and_before_1990 = Book.objects.filter(num_of_pages__gt = 200, published_on__lt = "1990-01-01")

    print(all_books)

    context = {

        "all_books": all_books,
        "all_books_after_2000": all_books_after_2000,
        "first_author": first_author,
        "books_greater_than_200_and_before_1990": books_greater_than_200_and_before_1990
    }

    return render(request, "library/all-authors.html", context)

def book_detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, "library/book_detail.html", {"book": book})

lms/templates/authors/book-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>This is the book list</title>
</head>
<body>
    <p>These are the book list...</p>
</body>
</html>

lms/templates/authors/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>This is the hompage</title>
</head>
<body>
    <p>This is the authors homepage...</p>
</body>
</html>

lms/templates/library/all-authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All authors</title>
</head>
<body>
    <p>These are all the authors...</p>

    <h3>These are all the books in Descending order</h3>
        <ul>
            {% for book in all_books %}
                <li><a href="{% url 'library:book_detail' book.pk %}">{{ book }}</a></li>

            {% endfor %}    
        </ul>


    <h3>These are all the books after 2000</h3>
        <ul>
            {% for book in all_books_after_2000 %}
                <li>{{ book }} -- {{ book.published_on }}</li>
            {% endfor %}    
        </ul>


    <h5>
        {{ first_author }}
    </h5>
        
   
    <h3>These are all the books greater than 200 and before 1990</h3>
        <ul>
            {% for book in books_greater_than_200_and_before_1990 %}
                <li>{{ book }} -- {{ book.published_on }} -- {{ book.num_of_pages }} pages</li>

            {% endfor %}    
        </ul>

</body>
</html>

lms/templates/library/book-signings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All book signings</title>
</head>
<body>
    <p>These are the upcoming book signings...</p>
</body>
</html>

lms/templates/library/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ book.title }}</title>
</head>
<body>
    <h4>
    These are the book details
    </h4>
    <p>
    {{ book.title }}
    </p>

    <p>
        {% if book.cover_image %}
        <img width="100" height= "100" src="{{ book.cover_image.url }}" alt="{{ book.title }} Image">
        
        {% else %}

            <p>You dont have a cover image</p>
        {% endif %}
    </p>
    <p>
        {{ book.author }}
    </p>
    <p>
        {{ book.num_of_pages }}
    </p>
    <p>
        {{ book.published_on }}
    </p>
</body>
</html>